import React from 'react';
import { Invoice } from '../../types/invoice';
import { useLanguage } from '../../context/LanguageContext';
import { formatCurrency } from '../../utils/formatUtils';
import './InvoiceCard.css';

interface InvoiceCardProps {
  invoice: Invoice;
  onClick: () => void;
}

export const InvoiceCard: React.FC<InvoiceCardProps> = ({ invoice, onClick }) => {
  const { t, language } = useLanguage();
  
  const getStatusBadge = (status: Invoice['status']) => {
    switch (status) {
      case 'paid':
        return <span className="status-badge paid">✓ {t('invoices.status.paid')}</span>;
      case 'sent':
        return <span className="status-badge sent">📧 {t('invoices.status.sent')}</span>;
      case 'overdue':
        return <span className="status-badge overdue">⚠️ {t('invoices.status.overdue')}</span>;
      case 'draft':
        return <span className="status-badge draft">📝 {t('invoices.status.draft')}</span>;
      case 'cancelled':
        return <span className="status-badge cancelled">✕ {language === 'pt-BR' ? 'Cancelado' : 'Cancelled'}</span>;
      default:
        return null;
    }
  };

  const daysUntilDue = () => {
    const dueDate = new Date(invoice.dueDate);
    const today = new Date();
    const diffTime = dueDate.getTime() - today.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays;
  };

  const daysOverdue = () => {
    if (invoice.status !== 'overdue') return 0;
    const dueDate = new Date(invoice.dueDate);
    const today = new Date();
    const diffTime = today.getTime() - dueDate.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  };

  return (
    <div className="invoice-card" onClick={onClick}>
      <div className="card-header">
        <div>
          <h3>{invoice.invoiceNumber}</h3>
          <p className="customer-name">{invoice.customerName}</p>
        </div>
        {getStatusBadge(invoice.status)}
      </div>

      <div className="card-body">
        <div className="invoice-info">
          <div className="info-row">
            <span className="info-label">{t('dashboard.dueDate')}:</span>
            <span className="info-value">
              {new Date(invoice.dueDate).toLocaleDateString(language === 'pt-BR' ? 'pt-BR' : 'en-US')}
              {invoice.status === 'sent' && (
                <span className={`days-indicator ${daysUntilDue() < 3 ? 'warning' : ''}`}>
                  {' '}({daysUntilDue()} {t('dashboard.days')})
                </span>
              )}
              {invoice.status === 'overdue' && (
                <span className="days-indicator overdue">
                  {' '}({daysOverdue()} {language === 'pt-BR' ? 'dias atrasado' : 'days overdue'})
                </span>
              )}
            </span>
          </div>

          <div className="info-row">
            <span className="info-label">{language === 'pt-BR' ? 'Subtotal' : 'Subtotal'}:</span>
            <span className="info-value">
              {formatCurrency(invoice.subtotal, language)}
            </span>
          </div>

          {invoice.lateFee && invoice.lateFee > 0 && (
            <div className="info-row late-fee-row">
              <span className="info-label">{language === 'pt-BR' ? 'Taxa de Atraso' : 'Late Fee'}:</span>
              <span className="info-value late-fee">
                {formatCurrency(invoice.lateFee, language)}
              </span>
            </div>
          )}

          <div className="info-row total-row">
            <span className="info-label">{t('stats.total')}:</span>
            <span className="info-value total">
              {formatCurrency(invoice.total, language)}
            </span>
          </div>

          {invoice.isRecurring && (
            <div className="info-row">
              <span className="info-label recurring-badge">
                🔄 {language === 'pt-BR' ? 'Recorrente' : 'Recurring'}
                {invoice.autoGenerated && (
                  <span className="auto-generated-badge"> 🤖 {t('invoice.autoGenerated')}</span>
                )}
              </span>
            </div>
          )}

          {invoice.emailSent && (
            <div className="info-row">
              <span className="info-label">📧 {language === 'pt-BR' ? 'Enviado em' : 'Sent on'}:</span>
              <span className="info-value">
                {invoice.emailSentDate && new Date(invoice.emailSentDate).toLocaleDateString(language === 'pt-BR' ? 'pt-BR' : 'en-US')}
              </span>
            </div>
          )}
        </div>
      </div>

      <div className="card-footer">
        <span className="card-arrow">→</span>
      </div>
    </div>
  );
};

