export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface LateFee {
  id: string;
  type: 'fixed' | 'percentage';
  value: number; // valor fixo em R$ ou percentual
  applyAfterDays: number; // aplicar após X dias de atraso
  description?: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  issueDate: string;
  dueDate: string;
  paidDate?: string;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  subtotal: number;
  lateFee?: number;
  lateFeeApplied?: boolean;
  lateFeeAppliedDate?: string;
  lateFeeRemindersSent?: string[]; // IDs dos lembretes já enviados
  taxes?: TaxAmount[]; // Impostos aplicados
  total: number;
  items: InvoiceItem[];
  notes?: string;
  isRecurring: boolean;
  recurringConfig?: RecurringConfig;
  emailSent?: boolean;
  emailSentDate?: string;
  autoGenerated?: boolean; // Se foi gerada automaticamente
  generatedFromCustomerId?: string; // ID do cliente que gerou esta invoice
  createdAt: string;
  updatedAt: string;
}

export interface TaxAmount {
  taxId: string;
  taxName: string;
  amount: number;
  type: 'percentage' | 'fixed';
}

export interface RecurringConfig {
  frequency: 'weekly' | 'biweekly' | 'monthly';
  startDate: string;
  endDate?: string; // opcional, se não tiver, continua indefinidamente
  dayOfWeek?: number; // 0-6 para weekly/biweekly
  dayOfMonth?: number; // 1-31 para monthly
  autoGenerate: boolean;
  lastGenerated?: string;
  nextGenerationDate?: string;
  customerId?: string; // Link direto ao cliente (para invoices baseadas em cliente)
  chargePerMonth?: number; // Valor mensal (para calcular valor por invoice)
}

export interface Payment {
  id: string;
  invoiceId: string;
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  amount: number;
  paymentDate: string;
  paymentMethod: 'cash' | 'credit_card' | 'debit_card' | 'bank_transfer' | 'pix' | 'check' | 'other';
  reference?: string; // número do cheque, comprovante, etc.
  notes?: string;
  recordedBy: string;
  createdAt: string;
}

export interface InvoiceFilters {
  status?: Invoice['status'];
  customerId?: string;
  dateFrom?: string;
  dateTo?: string;
  overdueOnly?: boolean;
}

