// Utilitários para exportação de dados (CSV e PDF)
import jsPDF from 'jspdf';
import { formatCurrency } from './formatUtils';

// Exportar dados para CSV
export const exportToCSV = <T extends Record<string, any>>(
  data: T[],
  filename: string,
  headers?: string[]
): void => {
  if (data.length === 0) {
    alert('Nenhum dado para exportar');
    return;
  }

  // Se não fornecer headers, usar as chaves do primeiro objeto
  const csvHeaders = headers || Object.keys(data[0]);
  
  // Criar linha de cabeçalho
  const headerRow = csvHeaders.join(',');
  
  // Criar linhas de dados
  const dataRows = data.map(row => {
    return csvHeaders.map(header => {
      const value = row[header];
      // Escapar valores que contêm vírgulas ou aspas
      if (value === null || value === undefined) return '';
      const stringValue = String(value);
      if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
        return `"${stringValue.replace(/"/g, '""')}"`;
      }
      return stringValue;
    }).join(',');
  });
  
  // Combinar tudo
  const csvContent = [headerRow, ...dataRows].join('\n');
  
  // Criar blob e fazer download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Exportar tabela para PDF
export const exportTableToPDF = (
  title: string,
  headers: string[],
  rows: string[][],
  filename: string,
  language: 'pt-BR' | 'en-US' = 'pt-BR'
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = margin;

  // Título
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, yPos);
  yPos += 15;

  // Calcular largura das colunas
  const colWidth = (pageWidth - 2 * margin) / headers.length;

  // Cabeçalho da tabela
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, 'F');
  
  headers.forEach((header, index) => {
    doc.text(header, margin + index * colWidth + 2, yPos);
  });
  yPos += 10;

  // Linhas de dados
  doc.setFont('helvetica', 'normal');
  rows.forEach((row) => {
    // Verificar se precisa de nova página
    if (yPos > 270) {
      doc.addPage();
      yPos = margin;
    }

    row.forEach((cell, index) => {
      const text = String(cell || '');
      doc.text(text.substring(0, 30), margin + index * colWidth + 2, yPos);
    });
    yPos += 7;
  });

  // Rodapé
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    language === 'pt-BR' ? 'Gerado por Bless Pool System' : 'Generated by Bless Pool System',
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  // Salvar
  doc.save(`${filename}.pdf`);
};

// Exportar lista de clientes para CSV
export const exportCustomersToCSV = (customers: any[]): void => {
  const data = customers.map(customer => ({
    'Nome': `${customer.firstName} ${customer.lastName}`,
    'Email': customer.email || '',
    'Telefone': customer.phone || '',
    'Endereço': customer.address,
    'Cidade': customer.city || '',
    'Estado': customer.state || '',
    'CEP': customer.zipCode || '',
    'Frequência': customer.frequency,
    'Tipo de Serviço': customer.typeOfService,
    'Dia de Serviço': customer.serviceDay || '',
    'Valor Mensal': customer.chargePerMonth || 0,
    'Status': customer.status,
  }));

  exportToCSV(data, 'clientes', Object.keys(data[0]));
};

// Exportar lista de invoices para CSV
export const exportInvoicesToCSV = (invoices: any[], language: 'pt-BR' | 'en-US' = 'pt-BR'): void => {
  const data = invoices.map(invoice => ({
    'Número': invoice.invoiceNumber,
    'Cliente': invoice.customerName,
    'Data de Emissão': new Date(invoice.issueDate).toLocaleDateString(language === 'pt-BR' ? 'pt-BR' : 'en-US'),
    'Data de Vencimento': new Date(invoice.dueDate).toLocaleDateString(language === 'pt-BR' ? 'pt-BR' : 'en-US'),
    'Status': invoice.status,
    'Subtotal': invoice.subtotal,
    'Taxa de Atraso': invoice.lateFee || 0,
    'Total': invoice.total,
  }));

  exportToCSV(data, 'invoices', Object.keys(data[0]));
};

// Exportar lista de work orders para CSV
export const exportWorkOrdersToCSV = (workOrders: any[]): void => {
  const data = workOrders.map(wo => ({
    'Número': wo.workOrderNumber,
    'Título': wo.title,
    'Cliente': wo.customerName,
    'Tipo': wo.type,
    'Prioridade': wo.priority,
    'Status': wo.status,
    'Técnico': wo.assignedTechnician || '',
    'Criada em': new Date(wo.createdAt).toLocaleDateString('pt-BR'),
  }));

  exportToCSV(data, 'work-orders', Object.keys(data[0]));
};

// Exportar relatório para PDF
export const exportReportToPDF = (
  reportTitle: string,
  headers: string[],
  data: any[],
  filename: string,
  language: 'pt-BR' | 'en-US' = 'pt-BR'
): void => {
  const rows = data.map(item => 
    headers.map(header => {
      const value = item[header];
      if (value === null || value === undefined) return '';
      if (typeof value === 'number') {
        // Formatar números como moeda se necessário
        if (header.toLowerCase().includes('total') || 
            header.toLowerCase().includes('preço') ||
            header.toLowerCase().includes('valor') ||
            header.toLowerCase().includes('revenue') ||
            header.toLowerCase().includes('expenses') ||
            header.toLowerCase().includes('profit')) {
          return formatCurrency(value, language);
        }
        return String(value);
      }
      return String(value);
    })
  );

  exportTableToPDF(reportTitle, headers, rows, filename, language);
};

