import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt-BR' | 'en-US';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Common
    'common.back': 'Voltar',
    'common.backToHub': 'Voltar ao Hub',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.new': 'Novo',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.logout': 'Sair',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.all': 'Todos',
    'common.allFem': 'Todas',
    'common.select': 'Selecione...',
    'common.close': 'Fechar',
    'common.remove': 'Remover',
    'common.add': 'Adicionar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.confirm': 'Confirmar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    
    // Pagination
    'pagination.showing': 'Mostrando',
    'pagination.of': 'de',
    'pagination.previous': 'Página anterior',
    'pagination.next': 'Próxima página',
    'pagination.page': 'Página',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.workArea': 'Work Area',
    'nav.customers': 'Cadastro de Clientes',
    'nav.invoices': 'Billing & Invoices',
    'nav.workOrders': 'Work Orders',
    'nav.settings': 'Configurações',
    'nav.inventory': 'Inventory',
    'nav.purchases': 'Purchases',
    'nav.reports': 'Relatórios',
    'nav.users': 'Gerenciar Usuários',
    'nav.companies': 'Empresas',
    
    // Admin Area
    'admin.welcome': 'Bem-vindo',
    'admin.area': 'Área administrativa - Acesso total ao sistema',
    
    // Login
    'login.title': 'BLESS POOL SYSTEM',
    'login.subtitle': 'Sistema de Gerenciamento',
    'login.username': 'Usuário',
    'login.password': 'Senha',
    'login.usernamePlaceholder': 'Digite seu usuário',
    'login.passwordPlaceholder': 'Digite sua senha',
    'login.submit': 'Entrar',
    'login.submitting': 'Entrando...',
    'login.error': 'Usuário ou senha inválidos',
    'login.errorGeneric': 'Erro ao fazer login. Tente novamente.',
    'login.testUsers': 'Usuários de teste:',
    'login.testAdmin': 'admin / qualquer senha',
    'login.testSupervisor': 'supervisor / qualquer senha',
    'login.testTechnician': 'tecnico / qualquer senha',
    
    // Dashboard
    'dashboard.title': 'Dashboard Administrativo',
    'dashboard.mainStats': 'Estatísticas Principais',
    'dashboard.activeCustomers': 'Clientes Ativos',
    'dashboard.inactiveCustomers': 'Clientes Inativos',
    'dashboard.inactive': 'inativos',
    'dashboard.newCustomers': 'Novos Clientes (Mês)',
    'dashboard.lostCustomers': 'Clientes Perdidos',
    'dashboard.lost': 'perdidos',
    'dashboard.overdueInvoices': 'Faturas em Atraso',
    'dashboard.billedThisMonth': 'Faturado (Mês)',
    'dashboard.billedThisYear': 'no ano',
    'dashboard.workOrders': 'Work Orders',
    'dashboard.workOrdersOpen': 'abertos',
    'dashboard.workOrdersInProgress': 'em andamento',
    'dashboard.waterAlerts': 'Alertas de Água',
    'dashboard.outOfStandard': 'Parâmetros fora do padrão',
    'dashboard.monthlyRevenue': 'Faturamento Mensal',
    'dashboard.clientVariation': 'Variação de Clientes',
    'dashboard.parameterAlerts': 'Alertas de Parâmetros',
    'dashboard.technicianPerformance': 'Performance dos Técnicos',
    'dashboard.period.30days': '30 dias',
    'dashboard.period.3months': '3 meses',
    'dashboard.period.6months': '6 meses',
    'dashboard.period.1year': '1 ano',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.readings': 'Readings',
    'settings.dosages': 'Dosages',
    'settings.checklist': 'Checklist',
    'settings.products': 'Products',
    'settings.tabs.readings': 'Readings',
    'settings.tabs.dosages': 'Dosages',
    'settings.tabs.checklist': 'Checklist',
    'settings.tabs.workOrderTypes': 'Work Order Types',
    'settings.tabs.products': 'Products',
    'settings.tabs.invoices': 'Configurações de Invoices',
    'settings.tabs.serviceMessages': 'Mensagens Padrão de Serviço',
    'settings.newType': 'Novo Tipo',
    'settings.deleteConfirm': 'Tem certeza que deseja excluir este tipo de work order?',
    'settings.noTypes': 'Nenhum tipo de work order cadastrado',
    'settings.fillRequired': 'Preencha todos os campos obrigatórios.',
    'settings.icon': 'Ícone',
    'settings.description': 'Descrição',
    'settings.color': 'Cor',
    'settings.activeType': 'Tipo Ativo',
    'settings.configureTypes': 'Configure os tipos de work orders e suas cores de identificação',
    'settings.readings.title': 'Padrões de Leituras (Readings)',
    'settings.readings.desc': 'Configure os padrões de leitura de químicos para uso nos serviços',
    'settings.readings.newStandard': 'Novo Padrão',
    'settings.readings.range': 'Faixa',
    'settings.readings.ideal': 'Ideal',
    'settings.readings.noReadings': 'Nenhum padrão de leitura cadastrado',
    'settings.readings.deleteConfirm': 'Tem certeza que deseja excluir este padrão de leitura?',
    'settings.dosages.title': 'Padrões de Dosagens',
    'settings.dosages.desc': 'Configure os padrões de dosagem de produtos químicos',
    'settings.dosages.newDosage': 'Nova Dosagem',
    'settings.dosages.defaultAmount': 'Quantidade Padrão',
    'settings.dosages.applicationNotes': 'Notas de Aplicação',
    'settings.dosages.noDosages': 'Nenhum padrão de dosagem cadastrado',
    'settings.dosages.deleteConfirm': 'Tem certeza que deseja excluir este padrão de dosagem?',
    'settings.checklist.title': 'Service Checklist',
    'settings.checklist.desc': 'Configure os itens básicos do checklist de serviços',
    'settings.checklist.newItem': 'Novo Item',
    'settings.checklist.category': 'Categoria',
    'settings.checklist.noChecklist': 'Nenhum item do checklist cadastrado',
    'settings.checklist.deleteConfirm': 'Tem certeza que deseja excluir este item do checklist?',
    'settings.products.title': 'Products',
    'settings.products.desc': 'Gerencie o estoque e informações dos produtos',
    'settings.products.newProduct': 'Novo Produto',
    'settings.products.category': 'Categoria',
    'settings.products.internalPrice': 'Preço Interno',
    'settings.products.minStock': 'Estoque Mínimo',
    'settings.products.supplier': 'Fornecedor',
    'settings.products.inactive': 'Inativo',
    'settings.products.noProducts': 'Nenhum produto cadastrado',
    'settings.products.deleteConfirm': 'Tem certeza que deseja excluir este produto?',
    
    // Language
    'language.title': 'Idioma',
    'language.ptBR': 'Português (Brasil)',
    'language.enUS': 'English (United States)',
    
    // Pages
    'page.customers': 'Cadastro de Clientes',
    'page.invoices': 'Billing & Invoices',
    'page.workOrders': 'Work Orders',
    'page.inventory': 'Inventory',
    'page.purchases': 'Purchases',
    'page.reports': 'Relatórios',
    
    // Customers Page
    'customers.searchPlaceholder': 'Buscar por nome ou endereço...',
    'customers.newCustomer': 'Novo Cliente',
    'customers.total': 'Total',
    'customers.active': 'Ativos',
    'customers.inactive': 'Inativos',
    'customers.notFound': 'Nenhum cliente encontrado',
    'customers.status': 'Status',
    'customers.technician': 'Técnico',
    
    // Invoices Page
    'invoices.searchPlaceholder': 'Buscar por número ou cliente...',
    'invoices.newInvoice': 'Nova Invoice',
    'invoices.notFound': 'Nenhuma invoice encontrada',
    'invoices.status': 'Status',
    'invoices.status.draft': 'Rascunho',
    'invoices.status.sent': 'Enviado',
    'invoices.status.paid': 'Pago',
    'invoices.status.overdue': 'Atrasado',
    'invoices.overdueOnly': 'Apenas em atraso',
    
    // Work Orders Page
    'workOrders.searchPlaceholder': 'Buscar por número, título ou cliente...',
    'workOrders.newWorkOrder': 'Nova Work Order',
    'workOrders.notFound': 'Nenhuma work order encontrada',
    'workOrders.status': 'Status',
    'workOrders.status.open': 'Aberta',
    'workOrders.status.inProgress': 'Em Andamento',
    'workOrders.status.completed': 'Concluída',
    'workOrders.type': 'Tipo',
    'workOrders.priority': 'Prioridade',
    'workOrders.priority.urgent': 'Urgente',
    'workOrders.priority.high': 'Alta',
    'workOrders.priority.medium': 'Média',
    'workOrders.priority.low': 'Baixa',
    'workOrders.technician': 'Técnico',
    
    // Inventory Page
    'inventory.newTransaction': 'Nova Transação',
    'inventory.productsInStock': 'Produtos em Estoque',
    'inventory.recentMovements': 'Movimentações Recentes',
    'inventory.totalProducts': 'Total de Produtos',
    'inventory.lowStock': 'Estoque Baixo',
    'inventory.totalValue': 'Valor Total',
    'inventory.notFound': 'Nenhum produto encontrado',
    'inventory.noMovements': 'Nenhuma movimentação registrada',
    'inventory.transaction': 'Transação',
    'inventory.transaction.new': 'Nova Transação de Estoque',
    'inventory.transaction.product': 'Produto',
    'inventory.transaction.type': 'Tipo de Transação',
    'inventory.transaction.type.entry': 'Entrada',
    'inventory.transaction.type.exit': 'Saída',
    'inventory.transaction.type.consumption': 'Consumo (Técnico)',
    'inventory.transaction.type.adjustment': 'Ajuste',
    'inventory.transaction.quantity': 'Quantidade',
    'inventory.transaction.date': 'Data',
    'inventory.transaction.technician': 'Técnico',
    'inventory.transaction.notes': 'Observações (opcional)',
    'inventory.transaction.notesPlaceholder': 'Observações sobre a transação...',
    'inventory.transaction.save': 'Salvar Transação',
    'inventory.transaction.fillRequired': 'Preencha todos os campos obrigatórios corretamente.',
    'inventory.transaction.selectTechnician': 'Selecione um técnico para consumo.',
    'inventory.transaction.unit': 'Unidade',
    
    // Purchases Page
    'purchases.newPurchase': 'Nova Compra',
    'purchases.editPurchase': 'Editar Compra',
    'purchases.totalPurchases': 'Total de Compras',
    'purchases.totalAmount': 'Valor Total',
    'purchases.thisMonthPurchases': 'Compras Este Mês',
    'purchases.thisMonthAmount': 'Gasto Este Mês',
    'purchases.notFound': 'Nenhuma compra encontrada',
    'purchases.purchaseNumber': 'Número da Compra',
    'purchases.supplier': 'Fornecedor',
    'purchases.supplierPlaceholder': 'Nome do fornecedor',
    'purchases.purchaseDate': 'Data da Compra',
    'purchases.items': 'Itens da Compra',
    'purchases.addItem': 'Adicionar Item',
    'purchases.item': 'Item',
    'purchases.product': 'Produto',
    'purchases.quantity': 'Quantidade',
    'purchases.unitPrice': 'Preço Unitário (R$)',
    'purchases.total': 'Total',
    'purchases.totalPurchase': 'Total da Compra',
    'purchases.noItems': 'Nenhum item adicionado. Clique em "Adicionar Item" para começar.',
    'purchases.receipt': 'Comprovante',
    'purchases.gallery': 'Galeria',
    'purchases.camera': 'Câmera',
    'purchases.capture': 'Capturar Foto',
    'purchases.receiptAlt': 'Comprovante',
    'purchases.notes': 'Observações',
    'purchases.notesPlaceholder': 'Observações sobre a compra...',
    'purchases.save': 'Salvar Compra',
    'purchases.totalValue': 'Valor Total',
    
    // Reports
    'reports.totalServices': 'Total de Serviços',
    'reports.totalHours': 'Total de Horas',
    'reports.totalSpent': 'Total Gasto',
    'reports.totalConsumed': 'Total Consumido',
    'reports.chemicalByCustomer': 'Consumo por Cliente',
    'reports.chemicalByTechnician': 'Consumo por Técnico',
    'reports.monthlyExpenses': 'Gastos Mensais',
    'reports.serviceTime': 'Tempo por Serviço',
    'reports.servicesByTechnician': 'Serviços por Técnico',
    'reports.chemicalHistory': 'Histórico Químico',
    'reports.monthlyComparison': 'Comparativo Mensal',
    'reports.consumptionByCustomer': 'Consumo de Químicos por Cliente',
    'reports.consumptionByCustomerDesc': 'Relatório detalhado do consumo de produtos químicos por cliente',
    'reports.consumptionByTechnician': 'Consumo de Químicos por Técnico',
    'reports.consumptionByTechnicianDesc': 'Relatório do consumo de produtos químicos por técnico',
    'reports.monthlyExpensesTitle': 'Gastos Mensais',
    'reports.monthlyExpensesDesc': 'Relatório de gastos mensais por categoria',
    'reports.serviceTimeTitle': 'Tempo Médio por Serviço',
    'reports.serviceTimeDesc': 'Estatísticas de tempo médio, mínimo e máximo por tipo de serviço',
    'reports.servicesByTechnicianTitle': 'Serviços Realizados por Técnico',
    'reports.servicesByTechnicianDesc': 'Estatísticas de serviços realizados por técnico',
    'reports.chemicalHistoryTitle': 'Histórico de Parâmetros Químicos',
    'reports.chemicalHistoryDesc': 'Histórico completo de leituras químicas por cliente',
    'reports.monthlyComparisonTitle': 'Comparativo Mensal',
    'reports.monthlyComparisonDesc': 'Comparação de métricas mensais (serviços, receita, gastos, lucro, clientes)',
    'reports.customer': 'Cliente',
    'reports.technician': 'Técnico',
    'reports.completedServices': 'Serviços Concluídos',
    'reports.averageTime': 'Tempo Médio',
    'reports.minTime': 'Tempo Mínimo',
    'reports.maxTime': 'Tempo Máximo',
    'reports.serviceType': 'Tipo de Serviço',
    'reports.month': 'Mês',
    'reports.services': 'Serviços',
    'reports.revenue': 'Receita',
    'reports.expenses': 'Gastos',
    'reports.profit': 'Lucro',
    'reports.customers': 'Clientes',
    'reports.products': 'Produtos',
    
    // Dashboard Components
    'dashboard.clients': 'clientes',
    'dashboard.client': 'Cliente',
    'dashboard.totalOverdue': 'Total em Atraso',
    'dashboard.quantity': 'Quantidade',
    'dashboard.invoices': 'faturas',
    'dashboard.value': 'Valor',
    'dashboard.dueDate': 'Vencimento',
    'dashboard.daysOverdue': 'Dias em Atraso',
    'dashboard.days': 'dias',
    'dashboard.workOrders.open': 'Abertos',
    'dashboard.workOrders.inProgress': 'Em Andamento',
    'dashboard.workOrders.completed': 'Concluídos',
    'dashboard.workOrders.type': 'Tipo',
    'dashboard.workOrders.technician': 'Técnico',
    'dashboard.workOrders.scheduled': 'Agendado',
    'dashboard.alerts.high': 'Alto',
    'dashboard.alerts.medium': 'Médio',
    'dashboard.alerts.low': 'Baixo',
    'dashboard.alerts.noAlerts': 'Nenhum alerta ativo',
    'dashboard.alerts.standard': 'Padrão',
    'dashboard.alerts.detected': 'Detectado',
    'dashboard.performance.technician': 'Técnico',
    'dashboard.performance.services': 'Serviços',
    'dashboard.performance.rating': 'Avaliação',
    'dashboard.performance.punctuality': 'Pontualidade',
    'dashboard.performance.revenue': 'Receita',
    
    // Service Page
    'service.checklist': 'Checklist',
    'service.readings': 'Leituras de Químicos',
    'service.dosages': 'Dosagens Aplicadas',
    'service.products': 'Produtos Utilizados',
    'service.photos': 'Fotos',
    'service.observations': 'Observações',
    'service.observationsPlaceholder': 'Adicione observações sobre o serviço...',
    'service.completeService': 'Complete Service',
    'service.skipService': 'Skip It',
    'service.add': 'Adicionar',
    'service.value': 'Valor',
    'service.noReadings': 'Nenhuma leitura adicionada',
    'service.noDosages': 'Nenhuma dosagem adicionada',
    'service.noProducts': 'Nenhum produto adicionado',
    'service.noPhotos': 'Nenhuma foto adicionada',
    'service.completed': 'Serviço concluído! Relatório enviado por e-mail ao cliente.',
    'service.completedError': 'Serviço concluído, mas houve um erro ao enviar o e-mail. O relatório foi salvo localmente.',
    'service.client': 'Cliente',
    
    // Work Area
    'workArea.title': 'Work Area',
    'workArea.pending': 'Pendentes',
    'workArea.viewRoute': 'Ver Rota no Mapa',
    'workArea.routeClients': 'Clientes da Rota',
    'workArea.viewing': 'Visualizando',
    'workArea.changeView': 'Trocar Visualização',
    'workArea.technician': 'Técnico',
    'workArea.user': 'Usuário',
    'workArea.dateSelector.previousDay': 'Dia anterior',
    'workArea.dateSelector.nextDay': 'Próximo dia',
    'workArea.dateSelector.today': 'Hoje',
    'workArea.client.status.completed': 'Concluído',
    'workArea.client.status.skipped': 'Pulado',
    'workArea.client.status.pending': 'Pendente',
    'workArea.client.serviceType.deep': 'Limpeza Profunda',
    'workArea.client.serviceType.repair': 'Reparo',
    'workArea.client.serviceType.regular': 'Regular',
    'workArea.client.noClients': 'Nenhum cliente agendado para esta data.',
    'workArea.map.title': 'Visualização da Rota',
    'workArea.map.loading': 'Carregando mapa...',
    'workArea.map.clientsOnRoute': 'clientes na rota',
    'workArea.map.optimizedRoute': 'Rota Otimizada:',
    'workArea.map.note1': 'Em produção, aqui será exibido um mapa interativo com Google Maps ou Mapbox',
    'workArea.map.note2': 'Os marcadores mostrarão todos os clientes e a linha conectará a rota otimizada',
    'workArea.map.routeSummary': 'Rota otimizada calculada com {count} paradas',
    
    // Supervisor Selector
    'supervisor.chooseMode': 'Escolha o Modo de Visualização',
    'supervisor.selectView': 'Selecione como deseja visualizar a Work Area:',
    'supervisor.myProfile': 'Meu Perfil',
    'supervisor.viewAs': 'Visualizar como',
    'supervisor.or': 'OU',
    'supervisor.linkedTechnicians': 'Técnicos Vinculados',
    
    // Customer Form
    'customer.edit': 'Editar Cliente',
    'customer.new': 'Novo Cliente',
    'customer.updated': 'Cliente atualizado com sucesso!',
    'customer.created': 'Cliente cadastrado com sucesso!',
    'customer.notFound': 'Cliente não encontrado',
    'customer.basicData': 'Dados Básicos',
    'customer.fillRequired': 'Preencha pelo menos primeiro nome, sobrenome e endereço',
    'customer.maxEmails': 'Máximo de 3 e-mails permitidos',
    'customer.maxPhones': 'Máximo de 3 telefones permitidos',
    'customerForm.basicData': 'Dados Básicos',
    'customerForm.firstName': 'Primeiro Nome',
    'customerForm.lastName': 'Sobrenome',
    'customerForm.address': 'Endereço',
    'customerForm.city': 'Cidade',
    'customerForm.state': 'Estado',
    'customerForm.zipCode': 'CEP',
    'customerForm.accessCodes': 'Códigos de Acesso',
    'customerForm.addCode': 'Adicionar Código',
    'customerForm.codeLabel': 'Label',
    'customerForm.code': 'Código',
    'customerForm.noCodes': 'Nenhum código adicionado',
    'customerForm.contacts': 'Contatos',
    'customerForm.emails': 'E-mails (máx. 3)',
    'customerForm.addEmail': 'Adicionar E-mail',
    'customerForm.phones': 'Telefones (máx. 3)',
    'customerForm.addPhone': 'Adicionar Telefone',
    'customerForm.serviceSettings': 'Configurações do Serviço',
    'customerForm.frequency': 'Frequência',
    'customerForm.chargePerMonth': 'Valor por Mês (R$)',
    'customerForm.typeOfService': 'Tipo de Serviço',
    'customerForm.typeOfService.pool': 'Piscina',
    'customerForm.typeOfService.poolSpa': 'Piscina + SPA',
    'customerForm.typeOfService.spa': 'SPA',
    'customerForm.serviceDay': 'Dia da Semana',
    'customerForm.startOn': 'Início em',
    'customerForm.stopAfter': 'Término em',
    'customerForm.stopAfter.noEnd': 'Sem Data de Término',
    'customerForm.minutesAtStop': 'Minutos na Parada',
    'customerForm.minutesAtStop.placeholder': 'Deixe em branco para padrão de 25 minutos',
    'customerForm.minutesAtStop.description': 'Usado para calcular o tempo da rota',
    'customerForm.responsibleTechnician': 'Técnico Responsável',
    'customerForm.status': 'Status',
    
    // Invoice
    'invoice.subtotal': 'Subtotal',
    'invoice.lateFee': 'Taxa de Atraso',
    'invoice.recurring': 'Recorrente',
    'invoice.sentOn': 'Enviado em',
    'invoice.daysOverdue': 'dias atrasado',
    'invoice.daysUntil': 'dias',
    'invoice.totalInvoices': 'Total de Invoices',
    'invoice.pendingPayment': 'Pendente de Pagamento',
    'invoice.overdueInvoices': 'Invoices em Atraso',
    'invoice.updated': 'Invoice atualizada com sucesso!',
    'invoice.created': 'Invoice criada com sucesso!',
    'invoice.emailSent': 'E-mail enviado com sucesso!',
    'invoice.autoGenerated': 'Gerada Automaticamente',
    'invoice.recurringTemplates': 'Templates de Invoices Recorrentes',
    'invoice.generateNow': 'Gerar Invoices Agora',
    'invoice.generateAll': 'Gerar Todas as Invoices Pendentes',
    'invoice.generated': 'Invoices geradas com sucesso!',
    'invoice.generatedCount': '{count} invoice(s) gerada(s)',
    'invoice.noCustomersToGenerate': 'Nenhum cliente elegível para geração de invoices',
    'invoice.nextGeneration': 'Próxima Geração',
    'invoice.lastGenerated': 'Última Gerada',
    'invoice.pauseGeneration': 'Pausar Geração',
    'invoice.resumeGeneration': 'Retomar Geração',
    'invoice.autoGenerateEnabled': 'Geração Automática Ativada',
    'invoice.autoGenerateDisabled': 'Geração Automática Desativada',
    'invoice.useCustomerSettings': 'Usar Configurações do Cliente',
    'invoice.customerSettingsApplied': 'Configurações do cliente aplicadas automaticamente',
    'invoice.preview': 'Pré-visualizar',
    'invoice.settings.title': 'Configurações de Invoices',
    'invoice.settings.description': 'Configure como as invoices são geradas, enviadas e cobradas',
    'invoice.settings.tabs.general': 'Geral',
    'invoice.settings.tabs.lateFee': 'Taxa de Atraso',
    'invoice.settings.tabs.taxes': 'Impostos',
    'invoice.settings.tabs.company': 'Empresa',
    'invoice.settings.general.title': 'Configurações Gerais',
    'invoice.settings.general.dueDateDays': 'Dias para Vencimento (Padrão)',
    'invoice.settings.general.dueDateDaysDesc': 'Número de dias após emissão para vencimento',
    'invoice.settings.general.sendDayOfWeek': 'Dia da Semana para Enviar',
    'invoice.settings.general.sendDayOfWeekDesc': 'Dia da semana para envio automático de invoices',
    'invoice.settings.general.sendDayOfMonth': 'Dia do Mês para Enviar',
    'invoice.settings.general.sendDayOfMonthDesc': 'Dia do mês para envio automático (1-31)',
    'invoice.settings.general.notSet': 'Não definido',
    'invoice.settings.lateFee.title': 'Configurações de Taxa de Atraso',
    'invoice.settings.lateFee.enabled': 'Ativar Taxa de Atraso',
    'invoice.settings.lateFee.type': 'Tipo de Taxa',
    'invoice.settings.lateFee.typeFixed': 'Valor Fixo',
    'invoice.settings.lateFee.typePercentage': 'Percentual',
    'invoice.settings.lateFee.percentage': 'Percentual (%)',
    'invoice.settings.lateFee.fixedAmount': 'Valor Fixo',
    'invoice.settings.lateFee.applyAfterDays': 'Aplicar Após (Dias)',
    'invoice.settings.lateFee.applyAfterDaysDesc': 'Aplicar taxa após X dias de atraso',
    'invoice.settings.lateFee.warningEnabled': 'Ativar Aviso de Taxa',
    'invoice.settings.lateFee.warningDaysBefore': 'Avisar Dias Antes',
    'invoice.settings.lateFee.warningDaysBeforeDesc': 'Avisar cliente X dias antes de aplicar taxa',
    'invoice.settings.lateFee.multipleReminders': 'Múltiplos Lembretes de Cobrança',
    'invoice.settings.lateFee.reminders': 'Lembretes de Cobrança',
    'invoice.settings.lateFee.addReminder': 'Adicionar Lembrete',
    'invoice.settings.lateFee.reminder': 'Lembrete',
    'invoice.settings.lateFee.daysAfterDue': 'Dias Após Vencimento',
    'invoice.settings.lateFee.sendReminder': 'Enviar Lembrete',
    'invoice.settings.lateFee.applyLateFee': 'Aplicar Taxa',
    'invoice.settings.lateFee.customAmount': 'Valor Personalizado',
    'invoice.settings.lateFee.optional': 'Opcional',
    'invoice.settings.lateFee.useDefault': 'Usar valor padrão',
    'invoice.settings.lateFee.customMessage': 'Mensagem Personalizada',
    'invoice.settings.lateFee.messagePlaceholder': 'Mensagem opcional para este lembrete',
    'invoice.settings.taxes.title': 'Configurações de Impostos',
    'invoice.settings.taxes.enabled': 'Ativar Impostos',
    'invoice.settings.taxes.taxesList': 'Lista de Impostos',
    'invoice.settings.taxes.addTax': 'Adicionar Imposto',
    'invoice.settings.taxes.tax': 'Imposto',
    'invoice.settings.taxes.name': 'Nome',
    'invoice.settings.taxes.type': 'Tipo',
    'invoice.settings.taxes.typePercentage': 'Percentual',
    'invoice.settings.taxes.typeFixed': 'Valor Fixo',
    'invoice.settings.taxes.percentage': 'Percentual (%)',
    'invoice.settings.taxes.fixedAmount': 'Valor Fixo',
    'invoice.settings.taxes.applyTo': 'Aplicar Sobre',
    'invoice.settings.taxes.applyToSubtotal': 'Subtotal',
    'invoice.settings.taxes.applyToTotal': 'Total',
    'invoice.settings.taxes.description': 'Descrição',
    'invoice.settings.taxes.descriptionPlaceholder': 'Descrição opcional do imposto',
    'invoice.settings.company.title': 'Informações da Empresa',
    'invoice.settings.company.name': 'Nome da Empresa',
    'invoice.settings.company.address': 'Endereço',
    'invoice.settings.company.phone': 'Telefone',
    'invoice.settings.company.email': 'E-mail',
    'invoice.settings.company.taxId': 'CNPJ/CPF',
    'invoice.settings.company.footerMessage': 'Mensagem do Rodapé',
    'invoice.settings.company.footerMessagePlaceholder': 'Mensagem que aparecerá no rodapé da invoice',
    'invoice.settings.company.termsAndConditions': 'Termos e Condições',
    'invoice.settings.company.termsPlaceholder': 'Termos e condições que aparecerão na invoice',
    'invoiceForm.basicInfo': 'Informações Básicas',
    'invoiceForm.number': 'Número da Invoice',
    'invoiceForm.customer': 'Cliente',
    'invoiceForm.issueDate': 'Data de Emissão',
    'invoiceForm.dueDate': 'Data de Vencimento',
    'invoiceForm.status': 'Status',
    'invoiceForm.items': 'Itens da Invoice',
    'invoiceForm.addItem': 'Adicionar Item',
    'invoiceForm.description': 'Descrição',
    'invoiceForm.quantity': 'Qtd',
    'invoiceForm.unitPrice': 'Preço Unit.',
    'invoiceForm.total': 'Total',
    'invoiceForm.itemDescriptionPlaceholder': 'Descrição do item',
    'invoiceForm.recurring': 'Invoice Recorrente',
    'invoiceForm.frequency': 'Frequência',
    'invoiceForm.startDate': 'Data de Início',
    'invoiceForm.endDate': 'Data de Término (opcional)',
    'invoiceForm.autoGenerate': 'Gerar automaticamente',
    'invoiceForm.observations': 'Observações',
    'invoiceForm.observationsPlaceholder': 'Observações adicionais...',
    'invoiceForm.save': 'Salvar Invoice',
    'invoiceForm.fillRequired': 'Preencha todos os campos obrigatórios',
    
    // Work Order
    'workOrder.created': 'Criada em',
    'workOrder.minEstimated': 'min estimados',
    'workOrder.updated': 'Work Order atualizada com sucesso!',
    'workOrder.createdSuccess': 'Work Order criada com sucesso!',
    'workOrder.completed': 'Work Order concluída com sucesso!',
    'workOrder.open': 'Abertas',
    'workOrder.cancelled': 'Cancelada',
    'workOrderForm.basicInfo': 'Informações Básicas',
    'workOrderForm.number': 'Número da Work Order',
    'workOrderForm.type': 'Tipo',
    'workOrderForm.priority': 'Prioridade',
    'workOrderForm.status': 'Status',
    'workOrderForm.customerAndTechnician': 'Cliente e Técnico',
    'workOrderForm.customer': 'Cliente',
    'workOrderForm.assignTechnician': 'Atribuir Técnico',
    'workOrderForm.notAssigned': 'Não atribuído',
    'workOrderForm.estimatedDuration': 'Duração Estimada (minutos)',
    'workOrderForm.description': 'Descrição',
    'workOrderForm.title': 'Título',
    'workOrderForm.titlePlaceholder': 'Título da Work Order',
    'workOrderForm.descriptionPlaceholder': 'Descreva o problema ou serviço necessário...',
    'workOrderForm.photos': 'Fotos',
    'workOrderForm.gallery': 'Galeria',
    'workOrderForm.camera': 'Câmera',
    'workOrderForm.close': 'Fechar',
    'workOrderForm.capturePhoto': 'Capturar Foto',
    'workOrderForm.observations': 'Observações',
    'workOrderForm.observationsPlaceholder': 'Observações adicionais...',
    'workOrderForm.save': 'Salvar Work Order',
    'workOrderForm.fillRequired': 'Preencha todos os campos obrigatórios',
    
    // Days of Week
    'days.monday': 'Segunda',
    'days.tuesday': 'Terça',
    'days.wednesday': 'Quarta',
    'days.thursday': 'Quinta',
    'days.friday': 'Sexta',
    'days.saturday': 'Sábado',
    'days.sunday': 'Domingo',
    
    // Service Types
    'serviceType.weekly': 'Semanal',
    'serviceType.biweekly': 'Quinzenal',
    
    // Common Stats
    'stats.total': 'Total',
    'stats.active': 'Ativos',
    'stats.inactive': 'Inativos',
    'stats.notFound': 'Não encontrado',
  },
  'en-US': {
    // Common
    'common.back': 'Back',
    'common.backToHub': 'Back to Hub',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.new': 'New',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.logout': 'Logout',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.all': 'All',
    'common.allFem': 'All',
    'common.select': 'Select...',
    'common.close': 'Close',
    'common.remove': 'Remove',
    'common.add': 'Add',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Pagination
    'pagination.showing': 'Showing',
    'pagination.of': 'of',
    'pagination.previous': 'Previous page',
    'pagination.next': 'Next page',
    'pagination.page': 'Page',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.workArea': 'Work Area',
    'nav.customers': 'Customers',
    'nav.invoices': 'Billing & Invoices',
    'nav.workOrders': 'Work Orders',
    'nav.settings': 'Settings',
    'nav.inventory': 'Inventory',
    'nav.purchases': 'Purchases',
    'nav.reports': 'Reports',
    'nav.users': 'Manage Users',
    'nav.companies': 'Companies',
    
    // Admin Area
    'admin.welcome': 'Welcome',
    'admin.area': 'Administrative area - Full system access',
    
    // Login
    'login.title': 'BLESS POOL SYSTEM',
    'login.subtitle': 'Management System',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'Enter your username',
    'login.passwordPlaceholder': 'Enter your password',
    'login.submit': 'Login',
    'login.submitting': 'Logging in...',
    'login.error': 'Invalid username or password',
    'login.errorGeneric': 'Error logging in. Please try again.',
    'login.testUsers': 'Test users:',
    'login.testAdmin': 'admin / any password',
    'login.testSupervisor': 'supervisor / any password',
    'login.testTechnician': 'technician / any password',
    
    // Dashboard
    'dashboard.title': 'Administrative Dashboard',
    'dashboard.mainStats': 'Main Statistics',
    'dashboard.activeCustomers': 'Active Customers',
    'dashboard.inactiveCustomers': 'Inactive Customers',
    'dashboard.inactive': 'inactive',
    'dashboard.newCustomers': 'New Customers (Month)',
    'dashboard.lostCustomers': 'Lost Customers',
    'dashboard.lost': 'lost',
    'dashboard.overdueInvoices': 'Overdue Invoices',
    'dashboard.billedThisMonth': 'Billed (Month)',
    'dashboard.billedThisYear': 'this year',
    'dashboard.workOrders': 'Work Orders',
    'dashboard.workOrdersOpen': 'open',
    'dashboard.workOrdersInProgress': 'in progress',
    'dashboard.waterAlerts': 'Water Alerts',
    'dashboard.outOfStandard': 'Out of standard parameters',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.clientVariation': 'Client Variation',
    'dashboard.parameterAlerts': 'Parameter Alerts',
    'dashboard.technicianPerformance': 'Technician Performance',
    'dashboard.period.30days': '30 days',
    'dashboard.period.3months': '3 months',
    'dashboard.period.6months': '6 months',
    'dashboard.period.1year': '1 year',
    
    // Settings
    'settings.title': 'Settings',
    'settings.readings': 'Readings',
    'settings.dosages': 'Dosages',
    'settings.checklist': 'Checklist',
    'settings.products': 'Products',
    'settings.tabs.readings': 'Readings',
    'settings.tabs.dosages': 'Dosages',
    'settings.tabs.checklist': 'Checklist',
    'settings.tabs.workOrderTypes': 'Work Order Types',
    'settings.tabs.products': 'Products',
    'settings.tabs.serviceMessages': 'Default Service Messages',
    'settings.readings.title': 'Reading Standards',
    'settings.readings.desc': 'Configure chemical reading standards for use in services',
    'settings.readings.newStandard': 'New Standard',
    'settings.readings.range': 'Range',
    'settings.readings.ideal': 'Ideal',
    'settings.readings.noReadings': 'No reading standards registered',
    'settings.readings.deleteConfirm': 'Are you sure you want to delete this reading standard?',
    'settings.dosages.title': 'Dosage Standards',
    'settings.dosages.desc': 'Configure chemical product dosage standards',
    'settings.dosages.newDosage': 'New Dosage',
    'settings.dosages.defaultAmount': 'Default Amount',
    'settings.dosages.applicationNotes': 'Application Notes',
    'settings.dosages.noDosages': 'No dosage standards registered',
    'settings.dosages.deleteConfirm': 'Are you sure you want to delete this dosage standard?',
    'settings.checklist.title': 'Service Checklist',
    'settings.checklist.desc': 'Configure basic service checklist items',
    'settings.checklist.newItem': 'New Item',
    'settings.checklist.category': 'Category',
    'settings.checklist.noChecklist': 'No checklist items registered',
    'settings.checklist.deleteConfirm': 'Are you sure you want to delete this checklist item?',
    'settings.products.title': 'Products',
    'settings.products.desc': 'Manage product inventory and information',
    'settings.products.newProduct': 'New Product',
    'settings.products.category': 'Category',
    'settings.products.internalPrice': 'Internal Price',
    'settings.products.minStock': 'Minimum Stock',
    'settings.products.supplier': 'Supplier',
    'settings.products.inactive': 'Inactive',
    'settings.products.noProducts': 'No products registered',
    'settings.products.deleteConfirm': 'Are you sure you want to delete this product?',
    'settings.newType': 'New Type',
    'settings.deleteConfirm': 'Are you sure you want to delete this work order type?',
    'settings.noTypes': 'No work order types registered',
    'settings.fillRequired': 'Please fill in all required fields.',
    'settings.icon': 'Icon',
    'settings.description': 'Description',
    'settings.color': 'Color',
    'settings.activeType': 'Active Type',
    'settings.configureTypes': 'Configure work order types and their identification colors',
    
    // Language
    'language.title': 'Language',
    'language.ptBR': 'Portuguese (Brazil)',
    'language.enUS': 'English (United States)',
    
    // Pages
    'page.customers': 'Customers',
    'page.invoices': 'Billing & Invoices',
    'page.workOrders': 'Work Orders',
    'page.inventory': 'Inventory',
    'page.purchases': 'Purchases',
    'page.reports': 'Reports',
    
    // Customers Page
    'customers.searchPlaceholder': 'Search by name or address...',
    'customers.newCustomer': 'New Customer',
    'customers.total': 'Total',
    'customers.active': 'Active',
    'customers.inactive': 'Inactive',
    'customers.notFound': 'No customers found',
    'customers.status': 'Status',
    'customers.technician': 'Technician',
    
    // Invoices Page
    'invoices.searchPlaceholder': 'Search by number or customer...',
    'invoices.newInvoice': 'New Invoice',
    'invoices.notFound': 'No invoices found',
    'invoices.status': 'Status',
    'invoices.status.draft': 'Draft',
    'invoices.status.sent': 'Sent',
    'invoices.status.paid': 'Paid',
    'invoices.status.overdue': 'Overdue',
    'invoices.overdueOnly': 'Overdue only',
    
    // Work Orders Page
    'workOrders.searchPlaceholder': 'Search by number, title or customer...',
    'workOrders.newWorkOrder': 'New Work Order',
    'workOrders.notFound': 'No work orders found',
    'workOrders.status': 'Status',
    'workOrders.status.open': 'Open',
    'workOrders.status.inProgress': 'In Progress',
    'workOrders.status.completed': 'Completed',
    'workOrders.type': 'Type',
    'workOrders.priority': 'Priority',
    'workOrders.priority.urgent': 'Urgent',
    'workOrders.priority.high': 'High',
    'workOrders.priority.medium': 'Medium',
    'workOrders.priority.low': 'Low',
    'workOrders.technician': 'Technician',
    
    // Inventory Page
    'inventory.newTransaction': 'New Transaction',
    'inventory.productsInStock': 'Products in Stock',
    'inventory.recentMovements': 'Recent Movements',
    'inventory.totalProducts': 'Total Products',
    'inventory.lowStock': 'Low Stock',
    'inventory.totalValue': 'Total Value',
    'inventory.notFound': 'No products found',
    'inventory.noMovements': 'No movements recorded',
    'inventory.transaction': 'Transaction',
    'inventory.transaction.new': 'New Inventory Transaction',
    'inventory.transaction.product': 'Product',
    'inventory.transaction.type': 'Transaction Type',
    'inventory.transaction.type.entry': 'Entry',
    'inventory.transaction.type.exit': 'Exit',
    'inventory.transaction.type.consumption': 'Consumption (Technician)',
    'inventory.transaction.type.adjustment': 'Adjustment',
    'inventory.transaction.quantity': 'Quantity',
    'inventory.transaction.date': 'Date',
    'inventory.transaction.technician': 'Technician',
    'inventory.transaction.notes': 'Notes (optional)',
    'inventory.transaction.notesPlaceholder': 'Notes about the transaction...',
    'inventory.transaction.save': 'Save Transaction',
    'inventory.transaction.fillRequired': 'Please fill in all required fields correctly.',
    'inventory.transaction.selectTechnician': 'Select a technician for consumption.',
    'inventory.transaction.unit': 'Unit',
    
    // Purchases Page
    'purchases.newPurchase': 'New Purchase',
    'purchases.editPurchase': 'Edit Purchase',
    'purchases.totalPurchases': 'Total Purchases',
    'purchases.totalAmount': 'Total Amount',
    'purchases.thisMonthPurchases': 'This Month Purchases',
    'purchases.thisMonthAmount': 'This Month Spending',
    'purchases.notFound': 'No purchases found',
    'purchases.purchaseNumber': 'Purchase Number',
    'purchases.supplier': 'Supplier',
    'purchases.supplierPlaceholder': 'Supplier name',
    'purchases.purchaseDate': 'Purchase Date',
    'purchases.items': 'Purchase Items',
    'purchases.addItem': 'Add Item',
    'purchases.item': 'Item',
    'purchases.product': 'Product',
    'purchases.quantity': 'Quantity',
    'purchases.unitPrice': 'Unit Price ($)',
    'purchases.total': 'Total',
    'purchases.totalPurchase': 'Purchase Total',
    'purchases.noItems': 'No items added. Click "Add Item" to start.',
    'purchases.receipt': 'Receipt',
    'purchases.gallery': 'Gallery',
    'purchases.camera': 'Camera',
    'purchases.capture': 'Capture Photo',
    'purchases.receiptAlt': 'Receipt',
    'purchases.notes': 'Notes',
    'purchases.notesPlaceholder': 'Notes about the purchase...',
    'purchases.save': 'Save Purchase',
    'purchases.totalValue': 'Total Value',
    
    // Reports
    'reports.totalServices': 'Total Services',
    'reports.totalHours': 'Total Hours',
    'reports.totalSpent': 'Total Spent',
    'reports.totalConsumed': 'Total Consumed',
    
    // Dashboard Components
    'dashboard.clients': 'clients',
    'dashboard.client': 'Client',
    'dashboard.totalOverdue': 'Total Overdue',
    'dashboard.quantity': 'Quantity',
    'dashboard.invoices': 'invoices',
    'dashboard.value': 'Value',
    'dashboard.dueDate': 'Due Date',
    'dashboard.daysOverdue': 'Days Overdue',
    'dashboard.days': 'days',
    'dashboard.workOrders.open': 'Open',
    'dashboard.workOrders.inProgress': 'In Progress',
    'dashboard.workOrders.completed': 'Completed',
    'dashboard.workOrders.type': 'Type',
    'dashboard.workOrders.technician': 'Technician',
    'dashboard.workOrders.scheduled': 'Scheduled',
    'dashboard.alerts.high': 'High',
    'dashboard.alerts.medium': 'Medium',
    'dashboard.alerts.low': 'Low',
    'dashboard.alerts.noAlerts': 'No active alerts',
    'dashboard.alerts.standard': 'Standard',
    'dashboard.alerts.detected': 'Detected',
    'dashboard.performance.technician': 'Technician',
    'dashboard.performance.services': 'Services',
    'dashboard.performance.rating': 'Rating',
    'dashboard.performance.punctuality': 'Punctuality',
    'dashboard.performance.revenue': 'Revenue',
    
    // Service Page
    'service.checklist': 'Checklist',
    'service.readings': 'Chemical Readings',
    'service.dosages': 'Applied Dosages',
    'service.products': 'Products Used',
    'service.photos': 'Photos',
    'service.observations': 'Observations',
    'service.observationsPlaceholder': 'Add observations about the service...',
    'service.completeService': 'Complete Service',
    'service.skipService': 'Skip It',
    'service.add': 'Add',
    'service.value': 'Value',
    'service.noReadings': 'No readings added',
    'service.noDosages': 'No dosages added',
    'service.noProducts': 'No products added',
    'service.noPhotos': 'No photos added',
    'service.completed': 'Service completed! Report sent to client by email.',
    'service.completedError': 'Service completed, but there was an error sending the email. The report was saved locally.',
    'service.client': 'Client',
    
    // Work Area
    'workArea.title': 'Work Area',
    'workArea.pending': 'Pending',
    'workArea.viewRoute': 'View Route on Map',
    'workArea.routeClients': 'Route Clients',
    'workArea.viewing': 'Viewing',
    'workArea.changeView': 'Change View',
    'workArea.technician': 'Technician',
    'workArea.user': 'User',
    'workArea.dateSelector.previousDay': 'Previous day',
    'workArea.dateSelector.nextDay': 'Next day',
    'workArea.dateSelector.today': 'Today',
    'workArea.client.status.completed': 'Completed',
    'workArea.client.status.skipped': 'Skipped',
    'workArea.client.status.pending': 'Pending',
    'workArea.client.serviceType.deep': 'Deep Clean',
    'workArea.client.serviceType.repair': 'Repair',
    'workArea.client.serviceType.regular': 'Regular',
    'workArea.client.noClients': 'No clients scheduled for this date.',
    'workArea.map.title': 'Route Visualization',
    'workArea.map.loading': 'Loading map...',
    'workArea.map.clientsOnRoute': 'clients on route',
    'workArea.map.optimizedRoute': 'Optimized Route:',
    'workArea.map.note1': 'In production, an interactive map with Google Maps or Mapbox will be displayed here',
    'workArea.map.note2': 'Markers will show all clients and the line will connect the optimized route',
    'workArea.map.routeSummary': 'Optimized route calculated with {count} stops',
    
    // Supervisor Selector
    'supervisor.chooseMode': 'Choose View Mode',
    'supervisor.selectView': 'Select how you want to view the Work Area:',
    'supervisor.myProfile': 'My Profile',
    'supervisor.viewAs': 'View as',
    'supervisor.or': 'OR',
    'supervisor.linkedTechnicians': 'Linked Technicians',
    'supervisor.status.active': 'active',
    
    // Customer Form
    'customer.edit': 'Edit Customer',
    'customer.new': 'New Customer',
    'customer.updated': 'Customer updated successfully!',
    'customer.created': 'Customer registered successfully!',
    'customer.notFound': 'Customer not found',
    'customer.basicData': 'Basic Data',
    'customer.fillRequired': 'Please fill in at least first name, last name and address',
    'customer.maxEmails': 'Maximum of 3 emails allowed',
    'customer.maxPhones': 'Maximum of 3 phones allowed',
    'customerForm.basicData': 'Basic Data',
    'customerForm.firstName': 'First Name',
    'customerForm.lastName': 'Last Name',
    'customerForm.address': 'Address',
    'customerForm.city': 'City',
    'customerForm.state': 'State',
    'customerForm.zipCode': 'ZIP Code',
    'customerForm.accessCodes': 'Access Codes',
    'customerForm.addCode': 'Add Code',
    'customerForm.codeLabel': 'Label',
    'customerForm.code': 'Code',
    'customerForm.noCodes': 'No codes added',
    'customerForm.contacts': 'Contacts',
    'customerForm.emails': 'Emails (max. 3)',
    'customerForm.addEmail': 'Add Email',
    'customerForm.phones': 'Phones (max. 3)',
    'customerForm.addPhone': 'Add Phone',
    'customerForm.serviceSettings': 'Service Settings',
    'customerForm.frequency': 'Frequency',
    'customerForm.chargePerMonth': 'Charge per Month ($)',
    'customerForm.typeOfService': 'Type of Service',
    'customerForm.typeOfService.pool': 'Pool',
    'customerForm.typeOfService.poolSpa': 'Pool + SPA',
    'customerForm.typeOfService.spa': 'SPA',
    'customerForm.serviceDay': 'Service Day',
    'customerForm.startOn': 'Start On',
    'customerForm.stopAfter': 'Stop After',
    'customerForm.stopAfter.noEnd': 'No End',
    'customerForm.minutesAtStop': 'Minutes at Stop',
    'customerForm.minutesAtStop.placeholder': 'Leave blank for default of 25 minutes',
    'customerForm.minutesAtStop.description': 'Used to calculate route time',
    'customerForm.responsibleTechnician': 'Responsible Technician',
    'customerForm.status': 'Status',
    
    // Invoice
    'invoice.subtotal': 'Subtotal',
    'invoice.lateFee': 'Late Fee',
    'invoice.recurring': 'Recurring',
    'invoice.sentOn': 'Sent on',
    'invoice.daysOverdue': 'days overdue',
    'invoice.daysUntil': 'days',
    'invoice.totalInvoices': 'Total Invoices',
    'invoice.pendingPayment': 'Pending Payment',
    'invoice.overdueInvoices': 'Overdue Invoices',
    'invoice.updated': 'Invoice updated successfully!',
    'invoice.created': 'Invoice created successfully!',
    'invoice.emailSent': 'Email sent successfully!',
    'invoice.autoGenerated': 'Auto Generated',
    'invoice.recurringTemplates': 'Recurring Invoice Templates',
    'invoice.generateNow': 'Generate Invoices Now',
    'invoice.generateAll': 'Generate All Pending Invoices',
    'invoice.generated': 'Invoices generated successfully!',
    'invoice.generatedCount': '{count} invoice(s) generated',
    'invoice.noCustomersToGenerate': 'No eligible customers for invoice generation',
    'invoice.nextGeneration': 'Next Generation',
    'invoice.lastGenerated': 'Last Generated',
    'invoice.pauseGeneration': 'Pause Generation',
    'invoice.resumeGeneration': 'Resume Generation',
    'invoice.autoGenerateEnabled': 'Auto Generation Enabled',
    'invoice.autoGenerateDisabled': 'Auto Generation Disabled',
    'invoice.useCustomerSettings': 'Use Customer Settings',
    'invoice.customerSettingsApplied': 'Customer settings applied automatically',
    'invoice.preview': 'Preview',
    'invoice.settings.title': 'Invoice Settings',
    'invoice.settings.description': 'Configure how invoices are generated, sent, and charged',
    'invoice.settings.tabs.general': 'General',
    'invoice.settings.tabs.lateFee': 'Late Fee',
    'invoice.settings.tabs.taxes': 'Taxes',
    'invoice.settings.tabs.company': 'Company',
    'invoice.settings.general.title': 'General Settings',
    'invoice.settings.general.dueDateDays': 'Days Until Due (Default)',
    'invoice.settings.general.dueDateDaysDesc': 'Number of days after issue date for due date',
    'invoice.settings.general.sendDayOfWeek': 'Day of Week to Send',
    'invoice.settings.general.sendDayOfWeekDesc': 'Day of week for automatic invoice sending',
    'invoice.settings.general.sendDayOfMonth': 'Day of Month to Send',
    'invoice.settings.general.sendDayOfMonthDesc': 'Day of month for automatic sending (1-31)',
    'invoice.settings.general.notSet': 'Not Set',
    'invoice.settings.lateFee.title': 'Late Fee Settings',
    'invoice.settings.lateFee.enabled': 'Enable Late Fee',
    'invoice.settings.lateFee.type': 'Fee Type',
    'invoice.settings.lateFee.typeFixed': 'Fixed Amount',
    'invoice.settings.lateFee.typePercentage': 'Percentage',
    'invoice.settings.lateFee.percentage': 'Percentage (%)',
    'invoice.settings.lateFee.fixedAmount': 'Fixed Amount',
    'invoice.settings.lateFee.applyAfterDays': 'Apply After (Days)',
    'invoice.settings.lateFee.applyAfterDaysDesc': 'Apply fee after X days overdue',
    'invoice.settings.lateFee.warningEnabled': 'Enable Fee Warning',
    'invoice.settings.lateFee.warningDaysBefore': 'Warn Days Before',
    'invoice.settings.lateFee.warningDaysBeforeDesc': 'Warn customer X days before applying fee',
    'invoice.settings.lateFee.multipleReminders': 'Multiple Payment Reminders',
    'invoice.settings.lateFee.reminders': 'Payment Reminders',
    'invoice.settings.lateFee.addReminder': 'Add Reminder',
    'invoice.settings.lateFee.reminder': 'Reminder',
    'invoice.settings.lateFee.daysAfterDue': 'Days After Due',
    'invoice.settings.lateFee.sendReminder': 'Send Reminder',
    'invoice.settings.lateFee.applyLateFee': 'Apply Late Fee',
    'invoice.settings.lateFee.customAmount': 'Custom Amount',
    'invoice.settings.lateFee.optional': 'Optional',
    'invoice.settings.lateFee.useDefault': 'Use default value',
    'invoice.settings.lateFee.customMessage': 'Custom Message',
    'invoice.settings.lateFee.messagePlaceholder': 'Optional message for this reminder',
    'invoice.settings.taxes.title': 'Tax Settings',
    'invoice.settings.taxes.enabled': 'Enable Taxes',
    'invoice.settings.taxes.taxesList': 'Tax List',
    'invoice.settings.taxes.addTax': 'Add Tax',
    'invoice.settings.taxes.tax': 'Tax',
    'invoice.settings.taxes.name': 'Name',
    'invoice.settings.taxes.type': 'Type',
    'invoice.settings.taxes.typePercentage': 'Percentage',
    'invoice.settings.taxes.typeFixed': 'Fixed Amount',
    'invoice.settings.taxes.percentage': 'Percentage (%)',
    'invoice.settings.taxes.fixedAmount': 'Fixed Amount',
    'invoice.settings.taxes.applyTo': 'Apply To',
    'invoice.settings.taxes.applyToSubtotal': 'Subtotal',
    'invoice.settings.taxes.applyToTotal': 'Total',
    'invoice.settings.taxes.description': 'Description',
    'invoice.settings.taxes.descriptionPlaceholder': 'Optional tax description',
    'invoice.settings.company.title': 'Company Information',
    'invoice.settings.company.name': 'Company Name',
    'invoice.settings.company.address': 'Address',
    'invoice.settings.company.phone': 'Phone',
    'invoice.settings.company.email': 'Email',
    'invoice.settings.company.taxId': 'Tax ID',
    'invoice.settings.company.footerMessage': 'Footer Message',
    'invoice.settings.company.footerMessagePlaceholder': 'Message that will appear in invoice footer',
    'invoice.settings.company.termsAndConditions': 'Terms and Conditions',
    'invoice.settings.company.termsPlaceholder': 'Terms and conditions that will appear on invoice',
    'invoiceForm.basicInfo': 'Basic Information',
    'invoiceForm.number': 'Invoice Number',
    'invoiceForm.customer': 'Customer',
    'invoiceForm.issueDate': 'Issue Date',
    'invoiceForm.dueDate': 'Due Date',
    'invoiceForm.status': 'Status',
    'invoiceForm.items': 'Invoice Items',
    'invoiceForm.addItem': 'Add Item',
    'invoiceForm.description': 'Description',
    'invoiceForm.quantity': 'Qty',
    'invoiceForm.unitPrice': 'Unit Price',
    'invoiceForm.total': 'Total',
    'invoiceForm.itemDescriptionPlaceholder': 'Item description',
    'invoiceForm.recurring': 'Recurring Invoice',
    'invoiceForm.frequency': 'Frequency',
    'invoiceForm.startDate': 'Start Date',
    'invoiceForm.endDate': 'End Date (optional)',
    'invoiceForm.autoGenerate': 'Auto Generate',
    'invoiceForm.observations': 'Observations',
    'invoiceForm.observationsPlaceholder': 'Additional observations...',
    'invoiceForm.save': 'Save Invoice',
    'invoiceForm.fillRequired': 'Please fill in all required fields',
    
    // Work Order
    'workOrder.created': 'Created on',
    'workOrder.minEstimated': 'min estimated',
    'workOrder.updated': 'Work Order updated successfully!',
    'workOrder.createdSuccess': 'Work Order created successfully!',
    'workOrder.completed': 'Work Order completed successfully!',
    'workOrder.open': 'Open',
    'workOrder.cancelled': 'Cancelled',
    'workOrderForm.basicInfo': 'Basic Information',
    'workOrderForm.number': 'Work Order Number',
    'workOrderForm.type': 'Type',
    'workOrderForm.priority': 'Priority',
    'workOrderForm.status': 'Status',
    'workOrderForm.customerAndTechnician': 'Customer and Technician',
    'workOrderForm.customer': 'Customer',
    'workOrderForm.assignTechnician': 'Assign Technician',
    'workOrderForm.notAssigned': 'Not Assigned',
    'workOrderForm.estimatedDuration': 'Estimated Duration (minutes)',
    'workOrderForm.description': 'Description',
    'workOrderForm.title': 'Title',
    'workOrderForm.titlePlaceholder': 'Work Order Title',
    'workOrderForm.descriptionPlaceholder': 'Describe the problem or service needed...',
    'workOrderForm.photos': 'Photos',
    'workOrderForm.gallery': 'Gallery',
    'workOrderForm.camera': 'Camera',
    'workOrderForm.close': 'Close',
    'workOrderForm.capturePhoto': 'Capture Photo',
    'workOrderForm.observations': 'Observations',
    'workOrderForm.observationsPlaceholder': 'Additional observations...',
    'workOrderForm.save': 'Save Work Order',
    'workOrderForm.fillRequired': 'Please fill in all required fields',
    
    // Days of Week
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',
    
    // Service Types
    'serviceType.weekly': 'Weekly',
    'serviceType.biweekly': 'Biweekly',
    
    // Common Stats
    'stats.total': 'Total',
    'stats.active': 'Active',
    'stats.inactive': 'Inactive',
    'stats.notFound': 'Not found',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('bless_pool_language');
    return (saved as Language) || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('bless_pool_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(new RegExp(`\\{${param}\\}`, 'g'), String(params[param]));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
